---
- name: Hardening user password (optional)
  hosts: VIRTUAL_M
  become: yes

  tasks:
    - name: Change config file for CentOS, Fedora, and EulerOS based on Red Hat 7.0
      lineinfile:
        state: present
        dest: "/etc/security/pwquality.conf"
        line: "enforce_for_root usercheck=1"
      when: ansible_facts['os_family'] == "RedHat"



# by material THE URBAN PENGUIN
# Administering Local Password Policies in CentOS
# not tested
